apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ecomm-deploy
  labels:
    ecomm: deploy
spec: 
  replicas: 3
  selector:
    matchLabels:
      ecomm: deploy
  template:
    metadata:
      name: pod-ecomm
      labels:
        ecomm: deploy
    spec:
      containers:
        - name: cont-ecomm
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "adham"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "ecommerce_db"
          volumeMounts:
            - name: ecomm-vol
              mountPath: /data
      volumes:
        - name: ecomm-vol
          persistentVolumeClaim:
            claimName: postgres-ecomm-pvc        
