apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ecomm-pvc
spec:
  volumeName: postgres-ecomm-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
        
