apiVersion: v1
kind: Service
metadata:
  name: flask-ecomm-service
spec:
  type: LoadBalancer
  selector: 
    ecomm: flask
  ports:
    - protocol: TCP
      nodePort: 30010
      port: 5000
      targetPort: 5000  
